In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("data/students_chatgpt_survey.xlsx")

In [3]:
df.head()

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,Q40g,Q40h,Q40i,Q40j,Q40k,Q40l,Q40m,Q40n,Q40o,source
0,Afghanistan,2.0,19,Afghanistan,f\'h\'h,2.0,1.0,2.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AR
1,Afghanistan,3.0,100,Afghanistan,No,1.0,1.0,3.0,1.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EN
2,Afghanistan,1.0,19,Angola,Alastqlql,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AR
3,Afghanistan,4.0,95,Antigua & Barbuda,Facultad de gastronomía,1.0,1.0,3.0,1.0,1.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,ES
4,Afghanistan,3.0,22,Czech Republic,Economics and management CZU,1.0,1.0,2.0,2.0,2.0,...,4.0,4.0,5.0,5.0,1.0,4.0,2.0,4.0,5.0,EN

In [4]:
print(df.columns.tolist())

['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10', 'Q11', 'Q12', 'Q13a', 'Q13b', 'Q13c', 'Q13d', 'Q13e', 'Q13f', 'Q13f_text', 'Q14', 'Q15', 'Q16', 'Q17', 'Q18a', 'Q18b', 'Q18c', 'Q18d', 'Q18e', 'Q18f', 'Q18g', 'Q18h', 'Q18i', 'Q18j', 'Q18k', 'Q18l', 'Q19a', 'Q19b', 'Q19c', 'Q19d', 'Q19e', 'Q19f', 'Q19g', 'Q19h', 'Q19i', 'Q19j', 'Q20', 'Q21a', 'Q21b', 'Q21c', 'Q21d', 'Q22a', 'Q22b', 'Q22c', 'Q22d', 'Q22e', 'Q22f', 'Q22g', 'Q22h', 'Q22i', 'Q22j', 'Q23a', 'Q23b', 'Q23c', 'Q23d', 'Q24a', 'Q24b', 'Q24c', 'Q24d', 'Q24e', 'Q24f', 'Q24g', 'Q25a', 'Q25b', 'Q25c', 'Q25d', 'Q26a', 'Q26b', 'Q26c', 'Q26d', 'Q26e', 'Q26f', 'Q26g', 'Q26h', 'Q26i', 'Q26j', 'Q27a', 'Q27b', 'Q27c', 'Q27d', 'Q27e', 'Q27f', 'Q27g', 'Q27h', 'Q27i', 'Q27j', 'Q28a', 'Q28b', 'Q28c', 'Q28d', 'Q28e', 'Q28f', 'Q28g', 'Q28h', 'Q28i', 'Q29a', 'Q29b', 'Q29c', 'Q29d', 'Q29e', 'Q29f', 'Q29g', 'Q29h', 'Q29i', 'Q30a', 'Q30b', 'Q30c', 'Q30d', 'Q30e', 'Q30f', 'Q30g', 'Q30h', 'Q30i', 'Q30j', 'Q30k', 'Q30l', 'Q31a', 'Q31b', 'Q31c', 'Q31d', 'Q32a', 'Q32b', 'Q32c', 'Q32d', 'Q32e', 'Q32f', 'Q32g', 'Q32h', 'Q32i', 'Q32j', 'Q32k', 'Q32l', 'Q32m', 'Q32n', 'Q32o', 'Q33', 'Q34', 'Q35a', 'Q35b', 'Q35c', 'Q35d', 'Q35e', 'Q35f', 'Q35g', 'Q35h', 'Q35i', 'Q35j', 'Q35k', 'Q35l', 'Q35m', 'Q35n', 'Q36', 'Q37', 'Q38', 'Q39', 'Q40a', 'Q40b', 'Q40c', 'Q40d', 'Q40e', 'Q40f', 'Q40g', 'Q40h', 'Q40i', 'Q40j', 'Q40k', 'Q40l', 'Q40m', 'Q40n', 'Q40o', 'source']

In [ ]:
# Group by country of study (Q4) and calculate the mean (which gives the percentage) 
df_map = df.groupby('Q4')['Is_Regular'].mean().reset_index()
df_map['Percentage_Regular'] = df_map['Is_Regular'] * 100

In [8]:
df.groupby('Q4')['Q15'].mean().reset_index()

                           Q4       Q15
0                 Afghanistan  1.000000
1                     Albania  2.035714
2                     Algeria  3.500000
3                     Andorra  2.600000
4                      Angola  2.642857
..                        ...       ...
115  United States of America  1.659574
116                   Vietnam  2.750000
117                     Yemen  2.500000
118                    Zambia  2.814607
119                  Zimbabwe  3.066667

[120 rows x 2 columns]